export const config = {
	RTE_NAME: '',
	RTE_ALT: '',
	RTE_PREHEADER: '',
	RTE_TYPE: '', //POSSIBLE VALUES: VEEVA, SFMC, PITCHER, MASSMAILING, WP, INIS
	RTE_SANOFI: '', // POSSIBLE VALUES: YES, NO - Controls whether to include survey links
  RTE_DIVISION:'', // ONLY FOR SFMC SANOFI, POSSIBLE VALUES: GENMED, VACCINES, SPECIALITY_CARE
	RTE_UNSUBSCRIBE_MAIL: 'mailto:noreply@example.com', //ONLY FOR MASSMAILING
}
